<center><b><h3>2: Calculating a moving average - using python</h3></b></center>

Hi, 
You are given a list of numbers J and a single number p.  Write a function to return the minimum and maximum averages of the sequences of p numbers in the list J.


    
For example:


    
    
# Array of numbers
    

J = [4, 4, 4, 9, 10, 11, 12]
    

# Length of sequences, p
    

p = 3
    


    
Here, the sequences will be:


    

    
(4,4,4)

    
(4,4,9)

    
(4,9,10)

    
(9,10,11)

    
(10,11,12)

    

    
    
    
From the above we can see that the minimum average will be 4 and the maximum average will be 11, which corresponds to the first and last sequences.
    
Solution will be written in Python for premium users.


You’ve accumulated 2 questions since joining our email list. Create a premium account to access detailed solutions to each problem (including this one) + our new Case studies.

In [1]:
def moving_average():
    #import libraries
    import pandas as pd
    import numpy as np
    
    #input array of numbers 
    J = np.array(input("Enter array of numbers separated by comma: ").split(","), dtype=np.int32)
    P = int(input('Enter Length of sequences: '))
    
    #output moving average
    seq = ()
    count = 0
    while ((len(seq) < len(J)) & (P < len(J))):
        seq = J[:P]
        J = J[1:]
        print(seq)
        count += 1
    else:
        print(J.astype(int))

In [2]:
moving_average()

Enter array of numbers separated by comma: 1,2,21,3,32,34,3,45,4,56,5,67,8,76,87,1,23,21,1
Enter Length of sequences: 4
[ 1  2 21  3]
[ 2 21  3 32]
[21  3 32 34]
[ 3 32 34  3]
[32 34  3 45]
[34  3 45  4]
[ 3 45  4 56]
[45  4 56  5]
[ 4 56  5 67]
[56  5 67  8]
[ 5 67  8 76]
[67  8 76 87]
[ 8 76 87  1]
[76 87  1 23]
[87  1 23 21]
[ 1 23 21  1]
